import React, { useState } from 'react';
import { Citation, SEOMetadata } from '../types';
import { ExternalLink, Key, Copy, Code, Eye, Search, Braces, Share2, Image as ImageIcon, Twitter, Linkedin, Loader2, Download, Globe, Link as LinkIcon } from 'lucide-react';

interface BlogViewProps {
  content: string;
  citations: Citation[];
  category: string;
  keywords: string[];
  seoMetadata?: SEOMetadata;
  onGenerateImage: (prompt: string) => Promise<string>;
}

export const BlogView: React.FC<BlogViewProps> = ({ content, citations, category, keywords, seoMetadata, onGenerateImage }) => {
  const [viewMode, setViewMode] = useState<'preview' | 'code' | 'seo' | 'social'>('preview');
  const [copied, setCopied] = useState(false);
  const [generatingImageIdx, setGeneratingImageIdx] = useState<number | null>(null);
  const [generatedImages, setGeneratedImages] = useState<{[key: number]: string}>({});

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleGenerateImage = async (prompt: string, idx: number) => {
    setGeneratingImageIdx(idx);
    try {
      const base64 = await onGenerateImage(prompt);
      setGeneratedImages(prev => ({...prev, [idx]: base64}));
    } catch (error) {
      console.error(error);
      alert("Failed to generate image. Please try again.");
    } finally {
      setGeneratingImageIdx(null);
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      
      {/* Keywords Box */}
      {keywords.length > 0 && (
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6">
           <div className="flex items-center justify-between mb-3">
             <h3 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
               <Key className="w-5 h-5 text-amber-500" />
               Focused SEO Keywords
             </h3>
             <button 
               onClick={() => navigator.clipboard.writeText(keywords.join(', '))}
               className="text-slate-400 hover:text-blue-600 transition-colors"
               title="Copy keywords to clipboard"
             >
               <Copy className="w-5 h-5" />
             </button>
           </div>
           <p className="text-sm text-slate-500 mb-3">These high-traffic search terms have been integrated into the blog below. Copy them for your metadata tags.</p>
           
           {/* Semantic DL Structure for Keywords */}
           <dl className="bg-slate-50 border border-slate-200 rounded-lg p-4 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
             {keywords.map((keyword, idx) => (
               <div key={idx} className="bg-white px-3 py-2 rounded border border-slate-200 shadow-sm flex flex-col transition-shadow hover:shadow-md">
                 <dt className="font-mono text-sm font-medium text-slate-700 truncate" title={keyword}>{keyword}</dt>
                 <dd className="text-[10px] text-slate-400 uppercase tracking-wider mt-1">Target Keyword</dd>
               </div>
             ))}
           </dl>
        </div>
      )}

      {/* Main Content Card */}
      <div className="bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden">
        
        {/* Control Bar */}
        <div className="bg-slate-50 px-8 py-4 border-b border-slate-100 flex justify-between items-center flex-wrap gap-4">
           <div className="flex items-center gap-2">
             <span className="bg-blue-100 text-blue-700 text-xs font-bold px-2 py-1 rounded uppercase tracking-wide">
               {category} Tax Blog
             </span>
             <span className="text-slate-400 text-xs">Generated by PEAKtax AI</span>
           </div>
           
           {/* View Toggles */}
           <div className="flex bg-white rounded-lg border border-slate-200 p-1 overflow-x-auto">
              <button
                onClick={() => setViewMode('preview')}
                className={`flex items-center gap-2 px-3 py-1.5 rounded text-sm font-medium transition-all whitespace-nowrap ${
                  viewMode === 'preview' 
                    ? 'bg-blue-50 text-blue-600' 
                    : 'text-slate-500 hover:text-slate-700'
                }`}
              >
                <Eye className="w-4 h-4" /> Preview
              </button>
              <button
                onClick={() => setViewMode('code')}
                className={`flex items-center gap-2 px-3 py-1.5 rounded text-sm font-medium transition-all whitespace-nowrap ${
                  viewMode === 'code' 
                    ? 'bg-blue-50 text-blue-600' 
                    : 'text-slate-500 hover:text-slate-700'
                }`}
              >
                <Code className="w-4 h-4" /> HTML
              </button>
              {seoMetadata && (
                <>
                  <button
                    onClick={() => setViewMode('seo')}
                    className={`flex items-center gap-2 px-3 py-1.5 rounded text-sm font-medium transition-all whitespace-nowrap ${
                      viewMode === 'seo' 
                        ? 'bg-blue-50 text-blue-600' 
                        : 'text-slate-500 hover:text-slate-700'
                    }`}
                  >
                    <Search className="w-4 h-4" /> SEO Metadata
                  </button>
                  <button
                    onClick={() => setViewMode('social')}
                    className={`flex items-center gap-2 px-3 py-1.5 rounded text-sm font-medium transition-all whitespace-nowrap ${
                      viewMode === 'social' 
                        ? 'bg-blue-50 text-blue-600' 
                        : 'text-slate-500 hover:text-slate-700'
                    }`}
                  >
                    <Share2 className="w-4 h-4" /> Social & Media
                  </button>
                </>
              )}
           </div>
        </div>

        {/* Content Render */}
        {viewMode === 'preview' && (
          <div className="p-8 md:p-12 max-w-none blog-content" dangerouslySetInnerHTML={{ __html: content }} />
        )}

        {viewMode === 'code' && (
          <div className="relative group">
            <button
              onClick={() => copyToClipboard(content)}
              className="absolute top-4 right-4 bg-white/10 hover:bg-white/20 text-white p-2 rounded-lg transition-all backdrop-blur-sm border border-white/10"
              title="Copy HTML"
            >
              {copied ? <span className="text-green-400 text-xs font-bold px-1">Copied!</span> : <Copy className="w-4 h-4" />}
            </button>
            <pre className="bg-slate-900 text-blue-100 p-6 overflow-auto h-[600px] text-sm font-mono leading-relaxed">
              {content}
            </pre>
          </div>
        )}

        {viewMode === 'seo' && seoMetadata && (
           <div className="p-8 bg-slate-50 space-y-8 h-[600px] overflow-auto">
              {/* Google SERP Preview */}
              <div className="space-y-2">
                <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider">Google Search Preview</h3>
                <div className="bg-white p-4 rounded-lg border border-slate-200 shadow-sm max-w-2xl">
                  <div className="flex items-center gap-2 mb-1">
                    <div className="w-7 h-7 rounded-full bg-slate-200 flex items-center justify-center text-xs text-slate-500">Logo</div>
                    <div className="text-sm text-slate-800">Our Tax Partner</div>
                  </div>
                  <div className="text-blue-800 text-xl font-medium hover:underline cursor-pointer mb-1 truncate">
                    {seoMetadata.metaTitle}
                  </div>
                  <div className="text-slate-600 text-sm leading-relaxed">
                    {seoMetadata.metaDescription}
                  </div>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <label className="text-sm font-medium text-slate-700 block">Page Title (Title Tag)</label>
                  <div className="relative">
                     <input 
                        readOnly 
                        value={seoMetadata.metaTitle} 
                        className="w-full px-4 py-2 bg-white border border-slate-300 rounded-lg text-slate-700 text-sm"
                     />
                     <button onClick={() => copyToClipboard(seoMetadata.metaTitle)} className="absolute right-2 top-2 text-slate-400 hover:text-blue-600"><Copy size={16}/></button>
                  </div>
                  <div className="text-xs text-slate-500 text-right">{seoMetadata.metaTitle.length} / 60 chars</div>
                </div>

                <div className="space-y-2">
                  <label className="text-sm font-medium text-slate-700 block">URL Slug</label>
                  <div className="relative">
                     <input 
                        readOnly 
                        value={seoMetadata.slug} 
                        className="w-full px-4 py-2 bg-white border border-slate-300 rounded-lg text-slate-700 text-sm font-mono"
                     />
                     <button onClick={() => copyToClipboard(seoMetadata.slug)} className="absolute right-2 top-2 text-slate-400 hover:text-blue-600"><Copy size={16}/></button>
                  </div>
                </div>

                <div className="md:col-span-2 space-y-2">
                  <label className="text-sm font-medium text-slate-700 block">Meta Description</label>
                  <div className="relative">
                     <textarea 
                        readOnly 
                        value={seoMetadata.metaDescription} 
                        className="w-full px-4 py-2 bg-white border border-slate-300 rounded-lg text-slate-700 text-sm h-24 resize-none"
                     />
                     <button onClick={() => copyToClipboard(seoMetadata.metaDescription)} className="absolute right-2 top-2 text-slate-400 hover:text-blue-600"><Copy size={16}/></button>
                  </div>
                  <div className="text-xs text-slate-500 text-right">{seoMetadata.metaDescription.length} / 160 chars</div>
                </div>
              </div>
              
              {/* Related Topics / Internal Linking */}
              {seoMetadata.relatedTopics && seoMetadata.relatedTopics.length > 0 && (
                <div className="space-y-3">
                   <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider flex items-center gap-2">
                     <LinkIcon size={16} /> Internal Linking Strategy
                   </h3>
                   <p className="text-xs text-slate-500">Suggested blogs to link to or create next to build an SEO topic cluster.</p>
                   <div className="grid gap-3">
                     {seoMetadata.relatedTopics.map((topic, idx) => (
                       <div key={idx} className="bg-white border border-slate-200 rounded-lg p-3 flex items-center justify-between group hover:border-blue-300 transition-all">
                         <div className="min-w-0">
                           <div className="text-sm font-medium text-slate-800">{topic.title}</div>
                           <div className="text-xs text-blue-600 font-mono truncate">{topic.url}</div>
                         </div>
                         <button 
                            onClick={() => copyToClipboard(topic.url)}
                            className="ml-2 p-2 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded-md"
                            title="Copy URL"
                         >
                           <Copy size={14} />
                         </button>
                       </div>
                     ))}
                   </div>
                </div>
              )}

              {/* JSON-LD Schema */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider flex items-center gap-2">
                    <Braces size={16} /> Structured Data (JSON-LD)
                  </h3>
                  <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full font-medium">Includes FAQPage Schema</span>
                </div>
                <div className="relative group">
                  <button
                    onClick={() => copyToClipboard(seoMetadata.schemaJSON)}
                    className="absolute top-4 right-4 bg-slate-800/10 hover:bg-slate-800/20 text-slate-700 p-2 rounded-lg transition-all border border-slate-200"
                    title="Copy Schema"
                  >
                    <Copy className="w-4 h-4" />
                  </button>
                  <pre className="bg-slate-100 text-slate-700 p-6 rounded-xl border border-slate-200 overflow-auto h-64 text-xs font-mono">
                    {JSON.stringify(JSON.parse(seoMetadata.schemaJSON), null, 2)}
                  </pre>
                </div>
                <p className="text-xs text-slate-500">Paste this code into the &lt;head&gt; or schema plugin of your CMS to enable Rich Snippets.</p>
              </div>
           </div>
        )}

        {viewMode === 'social' && seoMetadata && (
          <div className="p-8 bg-slate-50 space-y-8 h-[600px] overflow-auto">
            
            {/* Social Meta Tags (New Feature) */}
            <div>
              <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider flex items-center gap-2 mb-4">
                <Globe size={16} /> Social Meta Tags (Open Graph)
              </h3>
              <p className="text-sm text-slate-500 mb-4">
                Paste this code into your website's &lt;head&gt; tag. This ensures your blog displays the correct title, description, and image when shared on social media.
              </p>
              <div className="relative group">
                  <button
                    onClick={() => copyToClipboard(seoMetadata.socialMetaTags)}
                    className="absolute top-4 right-4 bg-white border border-slate-200 hover:bg-slate-50 text-slate-600 p-2 rounded-lg transition-all shadow-sm"
                    title="Copy Meta Tags"
                  >
                    <Copy className="w-4 h-4" />
                  </button>
                  <pre className="bg-slate-900 text-purple-300 p-6 rounded-xl overflow-auto text-xs font-mono leading-relaxed">
                    {seoMetadata.socialMetaTags}
                  </pre>
              </div>
            </div>

            <hr className="border-slate-200" />
            
            {/* Image Ideas */}
            <div>
              <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider flex items-center gap-2 mb-4">
                <ImageIcon size={16} /> AI Image Generation (Imagen 3)
              </h3>
              <p className="text-sm text-slate-500 mb-4">Generate a high-quality, copyright-free image for your blog post instantly.</p>
              
              <div className="grid md:grid-cols-1 gap-6">
                {seoMetadata.imageIdeas?.map((idea, idx) => (
                  <div key={idx} className="bg-white rounded-lg border border-slate-200 p-4 shadow-sm">
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs font-bold text-blue-600 uppercase">Option {idx + 1}</span>
                      <span className="text-xs text-slate-400">{idea.description}</span>
                    </div>
                    
                    <div className="grid md:grid-cols-3 gap-4">
                      {/* Prompt & Alt Text Column */}
                      <div className="md:col-span-2 space-y-3">
                        <div className="relative bg-slate-100 p-3 rounded-md border border-slate-200">
                          <div className="text-xs text-slate-400 font-medium mb-1 uppercase">Prompt</div>
                          <p className="text-sm text-slate-700 font-mono">{idea.prompt}</p>
                          <button onClick={() => copyToClipboard(idea.prompt)} className="absolute top-2 right-2 text-slate-400 hover:text-blue-600"><Copy size={14}/></button>
                        </div>
                        <div className="relative bg-green-50 p-3 rounded-md border border-green-100">
                          <div className="text-xs text-green-600 font-medium mb-1 uppercase">SEO Alt Text</div>
                          <p className="text-sm text-green-800">{idea.altText}</p>
                          <button onClick={() => copyToClipboard(idea.altText)} className="absolute top-2 right-2 text-green-400 hover:text-green-700"><Copy size={14}/></button>
                        </div>
                        <button 
                          onClick={() => handleGenerateImage(idea.prompt, idx)}
                          disabled={generatingImageIdx === idx}
                          className="w-full bg-blue-600 hover:bg-blue-700 text-white py-2 rounded-lg text-sm font-medium flex items-center justify-center gap-2 transition-all disabled:bg-blue-300"
                        >
                          {generatingImageIdx === idx ? <Loader2 className="w-4 h-4 animate-spin"/> : <ImageIcon className="w-4 h-4"/>}
                          {generatingImageIdx === idx ? "Generating Image..." : "Generate This Image"}
                        </button>
                      </div>

                      {/* Generated Image Column */}
                      <div className="flex items-center justify-center bg-slate-100 rounded-lg border border-slate-200 aspect-video overflow-hidden relative">
                        {generatedImages[idx] ? (
                          <>
                            <img src={generatedImages[idx]} alt="Generated" className="w-full h-full object-cover" />
                            <a 
                              href={generatedImages[idx]} 
                              download={`tax-blog-image-${idx}.png`}
                              className="absolute bottom-2 right-2 bg-black/70 text-white p-2 rounded-full hover:bg-black transition-colors"
                              title="Download Image"
                            >
                              <Download size={16} />
                            </a>
                          </>
                        ) : (
                          <div className="text-center text-slate-400 p-4">
                            {generatingImageIdx === idx ? (
                              <div className="flex flex-col items-center gap-2">
                                <Loader2 className="w-8 h-8 animate-spin text-blue-500"/>
                                <span className="text-xs">Creating image...</span>
                              </div>
                            ) : (
                              <>
                                <ImageIcon className="w-8 h-8 mx-auto mb-2 opacity-50" />
                                <span className="text-xs">No image generated yet</span>
                              </>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Social Posts */}
            <div>
              <h3 className="text-sm font-bold text-slate-700 uppercase tracking-wider flex items-center gap-2 mb-4">
                <Share2 size={16} /> Marketing Copy (For manual posting)
              </h3>
              
              <div className="grid md:grid-cols-2 gap-6">
                {/* LinkedIn */}
                <div className="bg-white rounded-lg border border-slate-200 p-5 shadow-sm">
                  <div className="flex items-center gap-2 mb-3 text-[#0077b5]">
                    <Linkedin size={20} />
                    <span className="font-bold text-sm">LinkedIn Post</span>
                  </div>
                  <div className="relative">
                    <textarea 
                      readOnly 
                      value={seoMetadata.socialPosts?.linkedin || "No post generated."}
                      className="w-full h-64 p-3 bg-slate-50 border border-slate-200 rounded-md text-sm text-slate-700 resize-none focus:outline-none"
                    />
                    <button onClick={() => copyToClipboard(seoMetadata.socialPosts?.linkedin || "")} className="absolute top-3 right-3 bg-white p-1.5 rounded shadow-sm text-slate-400 hover:text-[#0077b5]"><Copy size={16}/></button>
                  </div>
                </div>

                {/* Twitter */}
                <div className="bg-white rounded-lg border border-slate-200 p-5 shadow-sm">
                  <div className="flex items-center gap-2 mb-3 text-[#1DA1F2]">
                    <Twitter size={20} />
                    <span className="font-bold text-sm">Twitter / X Thread</span>
                  </div>
                  <div className="relative">
                    <textarea 
                      readOnly 
                      value={seoMetadata.socialPosts?.twitter || "No post generated."}
                      className="w-full h-64 p-3 bg-slate-50 border border-slate-200 rounded-md text-sm text-slate-700 resize-none focus:outline-none"
                    />
                    <button onClick={() => copyToClipboard(seoMetadata.socialPosts?.twitter || "")} className="absolute top-3 right-3 bg-white p-1.5 rounded shadow-sm text-slate-400 hover:text-[#1DA1F2]"><Copy size={16}/></button>
                  </div>
                </div>
              </div>
            </div>

          </div>
        )}
      </div>

      {/* Citations */}
      {citations.length > 0 && (
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6">
          <h3 className="text-lg font-semibold text-slate-800 mb-4 flex items-center gap-2">
            <ExternalLink className="w-5 h-5 text-blue-600" />
            Verified Sources
          </h3>
          <div className="grid gap-3 md:grid-cols-2">
            {citations.map((citation, idx) => (
              <a 
                key={idx} 
                href={citation.uri} 
                target="_blank" 
                rel="noopener noreferrer"
                className="group p-3 rounded-lg border border-slate-200 hover:border-blue-300 hover:bg-blue-50 transition-all flex flex-col"
              >
                <span className="text-sm font-medium text-slate-800 group-hover:text-blue-700 truncate">{citation.title}</span>
                <span className="text-xs text-slate-500 mt-1 truncate">{citation.uri}</span>
              </a>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};